version: "3.9"
services:
  mysql_db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    healthcheck:
      test: mysqladmin ping -h localhost -p$${MYSQL_ROOT_PASSWORD}
      interval: 2s
      timeout: 5s
      retries: 20
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: registration

  app:
    image: truonghatsts/registration
    ports:
      - "8080:8080"
    depends_on:
      mysql_db:
        condition: service_healthy